In [2]:
import pandas as pd

In [ ]:
def describe_df(df):
    descriptive_summary = df.describe(include="all").T
    descriptive_summary["n_unique"] = df.nunique()
    descriptive_summary["null_count"] = df.isnull().sum()
    descriptive_summary["skewness"] = df.skew(numeric_only=True)
    descriptive_summary["kurtosis"] = df.kurtosis(numeric_only=True)
    descriptive_summary["type"] = df.dtypes
    
    try:
        descriptive_summary = descriptive_summary.drop(columns=["unique", "top", "freq"])
    except:
        pass

    return descriptive_summary

In [3]:
ventas_cdmx_df = pd.read_excel('../data/_raw/ventas_CDMX_aspel_export.xlsx', skiprows=3)
ventas_cdmx_df

,FOLIO,FECHA,SUCURSAL,CLAVE_PROD,DESCRIPCION,CATEGORIA,CANTIDAD,PRECIO_UNIT,SUBTOTAL,IVA,TOTAL,FORMA_PAGO,RFC_CLIENTE,VENDEDOR,ESTATUS,__UNNAMED__,Unnamed: 15
0,10000,2023-01-08,CDMX-Norte,ARROZ_1KG_LA,Arroz 1kg La Merced,Abarrotes,2,24.93,49.86,7.98,N/D,Efectivo,CGPO985807XYZ,Marta L.,PAGADO,NaN,NaN
1,10001,2023-01-11,CDMX-Sur,ACEITE_1L_NU,Aceite 1L Nutrioli,Abarrotes,49,44.06,2158.7,345.39,2504.09,Efectivo,IGBL765545XYZ,Carlos R.,PAGADO,NaN,NaN
2,10002,2023-01-02,CDMX-Norte,SUAVITEL_800,Suavitel 800ml,Limpieza,24,58.72,1409.23,225.48,1634.71,Tarjeta,LVEJ840074123,Carlos R.,PAGADO,NaN,NaN
3,10003,2023-01-09,CDMX-Sur,SERVILLETAS_,Servilletas Kleenex x100,Higiene,16,28.38,454.15,72.66,526.81,Crédito 30 días,FAIG810716123,José G.,PAGADO,NaN,NaN
4,10004,2023-01-08,CDMX-Norte,PAPEL_HIGIÉN,Papel Higiénico Petalo x4,Higiene,30,45.26,1357.72,217.24,1574.96,Tarjeta,ZDMT757588ABC,Marta L.,PENDIENTE,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2236,12171,2024-12-23,CDMX-Sur,FRIJOL_BAYO_,Frijol bayo 1kg,Abarrotes,35,34.52,1208.36,193.34,1401.7,Transferencia,UJJB758586ABC,Ana P.,PAGADO,NaN,NaN
2237,12172,2024-12-02,CDMX-Sur,ACEITE_1L_NU,Aceite 1L Nutrioli,Abarrotes,15,41.55,623.29,99.73,723.02,Transferencia,RLLF849572XYZ,Ana P.,PAGADO,NaN,NaN
2238,12173,2024-12-09,CDMX-Sur,CLORO_CLORAL,Cloro Cloralex 1L,Limpieza,44,20.41,898.1,143.7,1041.8,Transferencia,ARMN946039XYZ,Marta L.,PAGADO,NaN,NaN
2239,12174,2024-12-18,CDMX-Sur,DETERGENTE_A,Detergente Ariel 1kg,Limpieza,40,80.73,3229.23,516.68,3745.91,Tarjeta,GWYO930931ABC,José G.,PAGADO,NaN,NaN
2240,12175,2024-12-28,CDMX-Norte,SUAVITEL_800,Suavitel 800ml,Limpieza,23,53.51,1230.69,196.91,1427.6,Tarjeta,VJTN734774XYZ,Carlos R.,PAGADO,NaN,NaN

In [ ]:
# FECHA
ventas_cdmx_df['ERROR_FECHA'] = ventas_cdmx_df['FECHA'].apply(
    lambda x: x if pd.to_datetime(x, errors='coerce') is pd.NaT else None
)

errores_fecha_unicos = ventas_cdmx_df['ERROR_FECHA'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_fecha_unicos)

ventas_cdmx_df['FECHA'] = pd.to_datetime(ventas_cdmx_df['FECHA'], errors='coerce')

Valores únicos que no pudieron convertirse:
['Sin fecha']

In [5]:
# DESCRIPCION
desc_unicos = ventas_cdmx_df['DESCRIPCION'].dropna().unique()
print("Desc unicos:")
print(desc_unicos)

Desc unicos:
['Arroz 1kg La Merced' 'Aceite 1L Nutrioli' 'Suavitel 800ml'
 'Servilletas Kleenex x100' 'Papel Higiénico Petalo x4' 'Sal 1kg La Fina'
 'Pinol 1L' 'Cloro Cloralex 1L' 'Detergente Ariel 1kg' 'Azúcar 1kg Zulka'
 'Jabón Roma 500g' 'Frijol bayo 1kg']

In [8]:
# Productos y descripcion
prod_desc_df = ventas_cdmx_df[['DESCRIPCION', 'CATEGORIA']].drop_duplicates()
prod_desc_df

                  DESCRIPCION  CATEGORIA
0         Arroz 1kg La Merced  Abarrotes
1          Aceite 1L Nutrioli  Abarrotes
2              Suavitel 800ml   Limpieza
3    Servilletas Kleenex x100    Higiene
4   Papel Higiénico Petalo x4    Higiene
6             Sal 1kg La Fina  Abarrotes
9                    Pinol 1L   Limpieza
11          Cloro Cloralex 1L   Limpieza
14       Detergente Ariel 1kg   Limpieza
17           Azúcar 1kg Zulka  Abarrotes
18            Jabón Roma 500g   Limpieza
41            Frijol bayo 1kg  Abarrotes

In [ ]:
# PRECIO_UNIT
ventas_cdmx_df['ERROR_PRECIO_UNIT'] = ventas_cdmx_df['PRECIO_UNIT'].apply(
    lambda x: x if pd.isna(pd.to_numeric(x, errors='coerce')) else None
)

errores_precio_unicos = ventas_cdmx_df['ERROR_PRECIO_UNIT'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_precio_unicos)

ventas_cdmx_df['PRECIO_UNIT'] = pd.to_numeric(ventas_cdmx_df['PRECIO_UNIT'], errors='coerce')

Valores únicos que no pudieron convertirse:
['N/D']

In [ ]:
# SUBTOTAL
ventas_cdmx_df['ERROR_SUBTOTAL'] = ventas_cdmx_df['SUBTOTAL'].apply(
    lambda x: x if pd.isna(pd.to_numeric(x, errors='coerce')) else None
)

errores_subtotal_unicos = ventas_cdmx_df['ERROR_SUBTOTAL'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_subtotal_unicos)

ventas_cdmx_df['SUBTOTAL'] = pd.to_numeric(ventas_cdmx_df['SUBTOTAL'], errors='coerce')

Valores únicos que no pudieron convertirse:
['N/D']

In [ ]:
# IVA
ventas_cdmx_df['ERROR_IVA'] = ventas_cdmx_df['IVA'].apply(
    lambda x: x if pd.isna(pd.to_numeric(x, errors='coerce')) else None
)

errores_iva_unicos = ventas_cdmx_df['ERROR_IVA'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_iva_unicos)

ventas_cdmx_df['IVA'] = pd.to_numeric(ventas_cdmx_df['IVA'], errors='coerce')

Valores únicos que no pudieron convertirse:
['N/D']

In [ ]:
# FORMA_PAGO
fp_unicos = ventas_cdmx_df['FORMA_PAGO'].dropna().unique()
print("fp unicos:")
print(fp_unicos)

fp unicos:
['Efectivo' 'Tarjeta' 'Crédito 30 días' 'Transferencia' 'Cheque']

In [ ]:
# ESTATUS
es_unicos = ventas_cdmx_df['ESTATUS'].dropna().unique()
print("ESTATUS unicos:")
print(es_unicos)

ESTATUS unicos:
['PAGADO' 'PENDIENTE' 'CANCELADO']

In [ ]:
# TOTAL
ventas_cdmx_df['ERROR_TOTAL'] = ventas_cdmx_df['TOTAL'].apply(
    lambda x: x if pd.isna(pd.to_numeric(x, errors='coerce')) else None
)

errores_total_unicos = ventas_cdmx_df['ERROR_TOTAL'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_total_unicos)

ventas_cdmx_df['TOTAL'] = pd.to_numeric(ventas_cdmx_df['TOTAL'], errors='coerce')

Valores únicos que no pudieron convertirse:
['N/D']

In [ ]:
# MY TOTAL
ventas_cdmx_df['my_total'] = ventas_cdmx_df['CANTIDAD'] * ventas_cdmx_df['PRECIO_UNIT'] * 1.16

In [ ]:
ventas_cdmx_df = ventas_cdmx_df.drop(columns=['ERROR_FECHA', 'ERROR_PRECIO_UNIT', 'ERROR_SUBTOTAL', 'ERROR_IVA', 'ERROR_TOTAL'])
descriptive_summary = describe_df(ventas_cdmx_df)
descriptive_summary

,count,mean,min,25%,50%,75%,max,std,n_unique,null_count,skewness,kurtosis,type
FOLIO,2241.0,11088.493083,10000.0,10545.0,11087.0,11630.0,12175.0,627.843393,2176,0,0.000041,-1.201506,int64
FECHA,2182,2024-01-03 23:34:55.325389568,2023-01-01 00:00:00,2023-06-29 06:00:00,2024-01-07 12:00:00,2024-07-05 00:00:00,2024-12-31 00:00:00,NaN,684,59,NaN,NaN,datetime64[ns]
SUCURSAL,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,NaN,NaN,object
CLAVE_PROD,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,0,NaN,NaN,object
DESCRIPCION,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,0,NaN,NaN,object
CATEGORIA,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,NaN,NaN,object
CANTIDAD,2241.0,25.602856,1.0,12.0,26.0,38.0,50.0,14.687436,50,0,-0.018307,-1.257857,int64
PRECIO_UNIT,2122.0,37.502606,11.05,25.705,32.085,45.2575,88.56,18.456139,1599,119,1.096706,0.726379,float64
SUBTOTAL,2122.0,961.195693,11.18,382.9525,796.985,1320.8775,4355.73,779.401635,2056,119,1.379844,2.172520,float64
IVA,2135.0,155.002267,1.79,61.3,128.76,213.015,696.92,125.36031,2009,106,1.364484,2.108935,float64
TOTAL,2140.0,1025.087701,-3857.67,368.11,879.18,1513.895,5052.65,1024.635985,2072,101,0.563390,2.385574,float64
FORMA_PAGO,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,0,NaN,NaN,object
RFC_CLIENTE,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2176,0,NaN,NaN,object
VENDEDOR,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,NaN,NaN,object
ESTATUS,2241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,NaN,NaN,object
__UNNAMED__,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2241,NaN,NaN,float64
Unnamed: 15,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2241,NaN,NaN,float64
my_total,2122.0,1123.53341,12.9688,442.3602,932.7096,1551.9756,5052.38,911.768649,2034,119,1.362084,2.087675,float64

In [ ]:
ventas_gdl_2023_df = pd.read_excel('../data/_raw/ventas_GDL_lupita_manual.xlsx', sheet_name='Ventas 2023')
ventas_gdl_2024_df = pd.read_excel('../data/_raw/ventas_GDL_lupita_manual.xlsx', sheet_name='Ventas 2024')

ventas_gdl_df = pd.concat([ventas_gdl_2023_df, ventas_gdl_2024_df], ignore_index=True)
new_ventas_gdl_df = ventas_gdl_df.copy()
ventas_gdl_df

,Fecha,Producto,Ctdad,Unidad,P. Unit,Total c/IVA,Forma de pago,Cliente,Notas / Obs,Vendedor
0,22/02/2023,Arroz 1kg La Merced,16,pzas,$22.93,425.62,Tarjeta,Restaurante Centro Hist.,NaN,Rod
1,24-10-2023,Frijol bayo 1kg,16,cajas,$ 35,$ 646,efectivo,Restaurante del Centro,Cancelar si no paga,Rodrigo V.
2,22/08/2023,Azúcar 1kg Zulka,20,NaN,$25.74,$597.17,TRANSFERENCIA,Restaurante Norte,NaN,Lupita
3,31/12/2023,Sal 1kg La Fina,5,piezas,$10.94,$ 63,TRANSFERENCIA,Papelería Lomas,falta factura,lupita
4,08/12/2023,Arroz 1kg La Merced,22,cjas,24,$630.73,transf,Tienda de abarrotes Sur,URGENTE,Rodrigo V.
...,...,...,...,...,...,...,...,...,...,...
768,30-10-2024,Frijol bayo 1kg,5,cjas,$33.62,$194.98,TRANSFERENCIA,Restaurante del Centro,revisar,Rodrigo V.
769,06/09/2024,Aceite 1L Nutrioli,7,cjas,$44.07,$357.82,TRANSFERENCIA,Tienda de abarrotes Norte,descuento aplicado,Rodrigo V.
770,26-01-2024,Cloro Cloralex 1L,20,piezas,$ 20,$472.89,efectivo,Minisuper Norte,NaN,LUPITA M.
771,29-10-2024,Suavitel 800ml,3,cjas,54.55,$189.83,cheque,Minisuper Sur,NaN,Rod
772,"January 13, 2024",Frijol bayo 1kg,26,pz,32.99,994.95,Tarjeta,Restaurante Lomas,NaN,LUPITA M.

In [ ]:
# FECHA
new_ventas_gdl_df = new_ventas_gdl_df.rename(columns={'Fecha': 'FECHA'})

new_ventas_gdl_df['ERROR_FECHA'] = new_ventas_gdl_df['FECHA'].apply(
    lambda x: x if pd.to_datetime(x, errors='coerce', format='mixed', dayfirst=True) is pd.NaT else None
)

errores_fecha_unicos = new_ventas_gdl_df['ERROR_FECHA'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_fecha_unicos)

new_ventas_gdl_df['FECHA'] = pd.to_datetime(new_ventas_gdl_df['FECHA'], errors='coerce', format='mixed', dayfirst=True)

new_ventas_gdl_df = new_ventas_gdl_df.dropna(subset='FECHA')

Valores únicos que no pudieron convertirse:
['SUBTOTAL MARCH 2023' 'SUBTOTAL JANUARY 2023' 'SUBTOTAL OCTOBER 2023'
 'SUBTOTAL SEPTEMBER 2023' 'SUBTOTAL APRIL 2023' 'SUBTOTAL FEBRUARY 2023'
 'SUBTOTAL JULY 2023' 'SUBTOTAL JUNE 2023' 'SUBTOTAL NOVEMBER 2023'
 'SUBTOTAL MAY 2023' 'SUBTOTAL AUGUST 2023' 'SUBTOTAL DECEMBER 2023'
 'SUBTOTAL NOVEMBER 2024' 'SUBTOTAL JUNE 2024' 'SUBTOTAL OCTOBER 2024'
 'SUBTOTAL AUGUST 2024' 'SUBTOTAL APRIL 2024' 'SUBTOTAL DECEMBER 2024'
 'SUBTOTAL MARCH 2024' 'SUBTOTAL JULY 2024' 'SUBTOTAL FEBRUARY 2024'
 'SUBTOTAL SEPTEMBER 2024' 'SUBTOTAL MAY 2024' 'SUBTOTAL JANUARY 2024']

In [ ]:
# PRODUCTO
new_ventas_gdl_df = new_ventas_gdl_df.rename(columns={'Producto': 'PRODUCTO'})
productos_unicos = new_ventas_gdl_df['PRODUCTO'].dropna().unique()
print("Productos unicos:")
print(productos_unicos)

Productos unicos:
['Arroz 1kg La Merced' 'Frijol bayo 1kg' 'Azúcar 1kg Zulka'
 'Sal 1kg La Fina' 'Cloro Cloralex 1L' 'Aceite 1L Nutrioli'
 'Papel Higiénico Petalo x4' 'Jabón Roma 500g' 'Detergente Ariel 1kg'
 'Pinol 1L' 'Suavitel 800ml' 'Servilletas Kleenex x100']

In [ ]:
# CANTIDAD
new_ventas_gdl_df = new_ventas_gdl_df.rename(columns={'Ctdad': 'CANTIDAD'})
new_ventas_gdl_df['ERROR_CANTIDAD'] = new_ventas_gdl_df['CANTIDAD'].apply(
    lambda x: x if pd.isna(pd.to_numeric(x, errors='coerce')) else None
)

errores_cantidad_unicos = new_ventas_gdl_df['ERROR_CANTIDAD'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_cantidad_unicos)

new_ventas_gdl_df['CANTIDAD'] = pd.to_numeric(new_ventas_gdl_df['CANTIDAD'], errors='coerce')

Valores únicos que no pudieron convertirse:
[]

In [ ]:
# PRECIO_UNIT
new_ventas_gdl_df = new_ventas_gdl_df.rename(columns={'P. Unit': 'PRECIO_UNIT'})

new_ventas_gdl_df['PRECIO_UNIT'] = (
    new_ventas_gdl_df['PRECIO_UNIT']
    .astype(str)
    .str.replace(r'[\$,]', '', regex=True)
    .str.strip()
)

new_ventas_gdl_df['ERROR_PRECIO_UNIT'] = new_ventas_gdl_df['PRECIO_UNIT'].apply(
    lambda x: x if pd.isna(pd.to_numeric(x, errors='coerce')) else None
)

errores_precio_unicos = new_ventas_gdl_df['ERROR_PRECIO_UNIT'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_precio_unicos)

new_ventas_gdl_df['PRECIO_UNIT'] = pd.to_numeric(new_ventas_gdl_df['PRECIO_UNIT'], errors='coerce')

Valores únicos que no pudieron convertirse:
[]

In [ ]:
# TOTAL
new_ventas_gdl_df = new_ventas_gdl_df.rename(columns={'Total c/IVA': 'TOTAL'})

new_ventas_gdl_df['TOTAL'] = (
    new_ventas_gdl_df['TOTAL']
    .astype(str)
    .str.replace(r'[\$,]', '', regex=True)
    .str.strip()
)

new_ventas_gdl_df['ERROR_TOTAL'] = new_ventas_gdl_df['TOTAL'].apply(
    lambda x: x if pd.isna(pd.to_numeric(x, errors='coerce')) else None
)

errores_precio_unicos = new_ventas_gdl_df['ERROR_TOTAL'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_precio_unicos)

new_ventas_gdl_df['TOTAL'] = pd.to_numeric(new_ventas_gdl_df['TOTAL'], errors='coerce')

Valores únicos que no pudieron convertirse:
[]

In [ ]:
# FORMA_PAGO
new_ventas_gdl_df = new_ventas_gdl_df.rename(columns={'Forma de pago': 'FORMA_PAGO'})

new_ventas_gdl_df['FORMA_PAGO'] = (
    new_ventas_gdl_df['FORMA_PAGO']
    .str.strip()
    .str.lower()
)

map_fp = {
    'efectivo': 'Efectivo',
    'tarjeta': 'Tarjeta',
    'credito': 'Crédito 30 días',
    'transferencia': 'Transferencia',
    'transf': 'Transferencia',
    'cheque': 'Cheque'
}

new_ventas_gdl_df['FORMA_PAGO'] = new_ventas_gdl_df['FORMA_PAGO'].map(map_fp)

fp_unicos = new_ventas_gdl_df['FORMA_PAGO'].dropna().unique()
print("fp unicos:")
print(fp_unicos)

fp unicos:
['Tarjeta' 'Efectivo' 'Transferencia' 'Cheque' 'Crédito 30 días']

In [ ]:
# CLIENTE
new_ventas_gdl_df = new_ventas_gdl_df.rename(columns={'Cliente': 'CLIENTE'})

In [ ]:
# Vendedor
new_ventas_gdl_df = new_ventas_gdl_df.rename(columns={'Vendedor': 'VENDEDOR'})

new_ventas_gdl_df['VENDEDOR'] = (
    new_ventas_gdl_df['VENDEDOR']
    .str.strip()
    .str.lower()
)

map_v = {
    'rod': 'Rodrigo',
    'rodrigo v.': 'Rodrigo',
    'lupita': 'Lupita',
    'lupita m.': 'Lupita'
}

new_ventas_gdl_df['VENDEDOR'] = new_ventas_gdl_df['VENDEDOR'].map(map_v)

v_unicos = new_ventas_gdl_df['VENDEDOR'].dropna().unique()
print("VENDEDOR unicos:")
print(v_unicos)

VENDEDOR unicos:
['Rodrigo' 'Lupita']

In [ ]:
new_ventas_gdl_df = new_ventas_gdl_df.drop(columns=['ERROR_FECHA', 'ERROR_CANTIDAD', 'Unidad', 'ERROR_PRECIO_UNIT', 'ERROR_TOTAL', 'Notas / Obs'])
descriptive_summary = describe_df(new_ventas_gdl_df)
descriptive_summary

,count,mean,min,25%,50%,75%,max,std,n_unique,null_count,skewness,kurtosis,type
FECHA,749,2024-01-02 08:21:47.343124224,2023-01-03 00:00:00,2023-07-13 00:00:00,2024-01-03 00:00:00,2024-06-28 00:00:00,2024-12-31 00:00:00,NaN,470,0,NaN,NaN,datetime64[ns]
PRODUCTO,749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,0,NaN,NaN,object
CANTIDAD,749.0,14.962617,1.0,7.0,15.0,23.0,30.0,8.69699,30,0,0.051142,-1.259439,int64
PRECIO_UNIT,749.0,35.785621,10.0,24.98,31.0,43.51,85.55,17.58605,519,0,1.188291,1.020078,float64
TOTAL,749.0,627.545274,14.48,254.89,516.3,889.55,2960.0,507.73153,722,0,1.436072,2.746833,float64
FORMA_PAGO,749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,0,NaN,NaN,object
CLIENTE,749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,0,NaN,NaN,object
VENDEDOR,749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,NaN,NaN,object

In [ ]:
new_ventas_gdl_df = new_ventas_gdl_df.sort_values(by='FECHA', ascending=True)
# new_ventas_gdl_df.to_excel("ventas_GDL.xlsx", index=False)

In [ ]:
gastos_operativos_df = pd.read_excel('../data/_raw/gastos_operativos_dueño.xlsx')
gastos_operativos_df

,fecha,sucursal,concepto,monto,comprobante,pagado_por,mes_contable,observaciones,periodo
0,17/01/2023,CDMX-Norte,Renta sucursal,18209.14,NaN,TC personal dueño,2023-01,ya deducible,Jan-23
1,01/11/2023,CDMX-Norte,Nómina,57978.15,Ticket,Transferencia empresa,2023-01,pendiente de factura,01/2023
2,02/01/2023,CDMX-Norte,Combustible y fletes,9051.21,Factura,TC personal dueño,2023-01,ya deducible,January 2023
3,25/01/2023,CDMX-Norte,Luz y agua,3625.49,NaN,Transferencia empresa,2023-01,pendiente de factura,01/2023
4,19 Jan 2023,CDMX-Norte,Seguro de mercancía,4082.05,Factura,Transferencia empresa,2023-01,NaN,2023-01
...,...,...,...,...,...,...,...,...,...
692,22/12/2024,Guadalajara,Papelería y consumibles,917.46,Sin comprobante,Efectivo caja,2024-12,ya deducible,December 2024
693,30/12/2024,Guadalajara,Mantenimiento,2067.25,NaN,Efectivo caja,2024-12,NaN,12/2024
694,13 Dec 2024,Guadalajara,Publicidad (FB/IG),5581.30,Sin comprobante,Transferencia empresa,2024-12,NaN,2024-12
695,12/11/2024,Guadalajara,Contabilidad externa,4500.00,Sin comprobante,Efectivo caja,2024-12,NaN,2024-12
696,12/23/2024,Guadalajara,Imprevistos,2582.92,Factura,Transferencia empresa,2024-12,pendiente de factura,December 2024

In [ ]:
# FECHA y Periodo
gastos_operativos_df = gastos_operativos_df.rename(columns={'fecha': 'FECHA', 'periodo': 'PERIODO'})

gastos_operativos_df['FECHA'] = pd.to_datetime(gastos_operativos_df['FECHA'], errors='coerce', format='mixed', dayfirst=True)

gastos_operativos_df['ERROR_PERIODO'] = gastos_operativos_df['PERIODO'].apply(
    lambda x: x if pd.to_datetime(x, errors='coerce', format='mixed', dayfirst=True) is pd.NaT else None
)

errores_periodo_unicos = gastos_operativos_df['ERROR_PERIODO'].dropna().unique()

print("Valores únicos que no pudieron convertirse:")
print(errores_periodo_unicos)

Valores únicos que no pudieron convertirse:
['Jan-23' 'Feb-23' 'Mar-23' 'Apr-23' 'May-23' 'Jun-23' 'Jul-23' 'Aug-23'
 'Sep-23' 'Oct-23' 'Nov-23' 'Dec-23' 'Jan-24' 'Feb-24' 'Mar-24' 'Apr-24'
 'May-24' 'Jun-24' 'Jul-24' 'Aug-24' 'Sep-24' 'Oct-24' 'Nov-24' 'Dec-24']

In [ ]:
format_especifico = pd.to_datetime(gastos_operativos_df['PERIODO'], format='%b-%y', errors='coerce')
format_flexible = pd.to_datetime(gastos_operativos_df['PERIODO'], errors='coerce', dayfirst=True, format='mixed')

gastos_operativos_df['PERIODO'] = format_especifico.fillna(format_flexible)

In [ ]:
# CONCEPTO y MONTO
gastos_operativos_df = gastos_operativos_df.rename(columns={'concepto': 'CONCEPTO', 'monto': 'MONTO'})
concepto_unicos = gastos_operativos_df['CONCEPTO'].dropna().unique()
print("concepto unicos:")
print(concepto_unicos)

concepto unicos:
['Renta sucursal' 'Nómina' 'Combustible y fletes' 'Luz y agua'
 'Seguro de mercancía' 'Papelería y consumibles' 'Mantenimiento'
 'Publicidad (FB/IG)' 'Contabilidad externa' 'Imprevistos']

In [ ]:
# COMPROBANTE y OBSERVACIONES
gastos_operativos_df = gastos_operativos_df.rename(columns={'comprobante': 'COMPROBANTE', 'observaciones': 'OBSERVACIONES'})
comprobante_unicos = gastos_operativos_df['COMPROBANTE'].dropna().unique()
print("comprobante unicos:")
print(comprobante_unicos)

comprobante unicos:
['Ticket' 'Factura' 'Sin comprobante' 'Recibo']

In [ ]:
# FORMA_PAGO
gastos_operativos_df = gastos_operativos_df.rename(columns={'pagado_por': 'FORMA_PAGO'})
pagado_por_unicos = gastos_operativos_df['FORMA_PAGO'].dropna().unique()
print("FORMA_PAGO unicos:")
print(pagado_por_unicos)

FORMA_PAGO unicos:
['TC personal dueño' 'Transferencia empresa' 'Cheque' 'Efectivo caja']

In [ ]:
gastos_operativos_df = gastos_operativos_df.drop(columns=['mes_contable', 'ERROR_PERIODO'])
descriptive_summary = describe_df(gastos_operativos_df)
descriptive_summary

,count,mean,min,25%,50%,75%,max,std,n_unique,null_count,skewness,kurtosis,type
FECHA,697,2023-12-30 04:32:42.697274112,2023-01-02 00:00:00,2023-07-04 00:00:00,2023-12-23 00:00:00,2024-06-26 00:00:00,2024-12-30 00:00:00,NaN,435,0,NaN,NaN,datetime64[ns]
sucursal,697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,NaN,NaN,object
CONCEPTO,697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,0,NaN,NaN,object
MONTO,697.0,14267.477102,278.26,4075.32,5200.15,14954.27,89680.89,21083.448922,616,0,2.323857,4.205438,float64
COMPROBANTE,557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,140,NaN,NaN,object
FORMA_PAGO,697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,NaN,NaN,object
OBSERVACIONES,347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,350,NaN,NaN,object
PERIODO,697,2023-12-14 21:31:14.892396288,2023-01-01 00:00:00,2023-07-01 00:00:00,2023-12-01 00:00:00,2024-06-01 00:00:00,2024-12-01 00:00:00,NaN,24,0,NaN,NaN,datetime64[ns]

In [ ]:
sucursales = gastos_operativos_df['sucursal'].unique()
sucursales

array(['CDMX-Norte', 'CDMX-Sur', 'Guadalajara'], dtype=object)

In [ ]:
# for s in sucursales:
#     df_temp = gastos_operativos_df[gastos_operativos_df['sucursal'] == s].drop(columns=['sucursal'])
    
#     nombre_archivo = f'../data/processed/gastos_operativos_{s}.xlsx'
#     df_temp.to_excel(nombre_archivo, index=False)
    
#     print(f'Archivo {nombre_archivo} creado con éxito.')

Archivo ../data/processed/gastos_operativos_CDMX-Norte.xlsx creado con éxito.
Archivo ../data/processed/gastos_operativos_CDMX-Sur.xlsx creado con éxito.
Archivo ../data/processed/gastos_operativos_Guadalajara.xlsx creado con éxito.